# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30008  # Project requirement
  selector:
    app: web-app
